In [7]:
!pip install opencv-python

In [ ]:
import cv2
import time

# Initialize the laptop's camera (typically camera 0 is the default camera)
cam_port = 0
cam = cv2.VideoCapture(cam_port)

# Check if the camera opened successfully
if not cam.isOpened():
    print("Error: Could not access the camera")
else:
    # Allow the camera to warm up
    time.sleep(2)
    
    # Try to read from the camera
    result, image = cam.read()
    
    if result:
        # Display the captured image
        cv2.imshow("Captured Image", image)

        # Save the image to your working directory
        cv2.imwrite("captured_image.png", image)
        
        # Wait for a key press to close the image window
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    else:
        print("No image detected. Please try again.")

# Release the camera resource
cam.release()


In [8]:
#Reading an image
import cv2
image = cv2.imread("captured_image.png")
cv2.imshow("Image Capture" ,image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#capture the Image
import cv2
cam_port = 0
cam = cv2.VideoCapture(cam_port)

if not cam.isOpened():
    print("The Camera is Not Working")
else:
    result , image = cam.read()
    if result:
        filename = input("Enter  the name of image")
        cv2.imwrite(f"{filename}.png",image)
        resized_image = cv2.resize(image,(400,400))
        cv2.imshow("Resized Image",resized_image)
        print(f"image is saved as {filename}.png")
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    else:
        print("No image detected")
        

cam.release()

Enter  the name of image h


image is saved as h.png


In [55]:
import cv2
image = cv2.imread("Image.png")
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray",gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [66]:
import cv2
cv2.imread("Image.png")
height, width = image.shape[:2]  
print(f"The height is {height} pixels")
print(f"The width is {width} pixels")

The height is 480 pixels
The width is 640 pixels


In [2]:
import cv2
image = cv2.imread("Image.png")
edge = cv2.Canny(image, 50, 100)
cv2.imshow("Edge Detetction",edge)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [55]:
import cv2
cam = cv2.VideoCapture(0)
if not cam.isOpened():
    print("The Camera is not working")
else :
    result, image = cam.read()
    if result:
        filename = input("Write the filename")
        
        
        gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
        edge = cv2.Canny(gray_image,50,100)
        # cv2.imshow("Captured Image",image)
        cv2.imshow("Captured Image",edge)
        cv2.imwrite(f"{filename}.png",edge)
        print(f"The file is saved {filename}")
        cv2.waitKey(0)
        cv2.destroyAllWindows()

    else:
        print("Not Captured")

cam.release()
    

Write the filename n


The file is saved n


In [53]:
import cv2
image = cv2.imread("Image.png")
edge = cv2.Canny(image,50,100)
cv2.imwrite("gphoto.png",edge)
cv2.imshow("Gray",edge)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
!pip install numpy


In [10]:
import numpy as np
z = np.ones(4)
z

array([1., 1., 1., 1.])

In [12]:
type(z)

numpy.ndarray

In [14]:
import pandas as pd

# Creating a Series
s = pd.Series([1, 3, 5, 7, 9])
print(s)

# Creating a Series with custom index
s2 = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd', 'e'])
print(s2)


0    1
1    3
2    5
3    7
4    9
dtype: int64
a    1
b    3
c    5
d    7
e    9
dtype: int64


In [23]:
s = pd.Series([1,2,3,4])
s2 = pd.Series([1,2,3,4],index = ["A","B","C","D"])
print(s2)

A    1
B    2
C    3
D    4
dtype: int64


In [25]:
# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Paris', 'Berlin']}

df = pd.DataFrame(data)
print(df)

# Accessing columns
print(df['Name'])

# Accessing rows using loc or iloc
print(df.loc[0])  # Row by label
print(df.iloc[1])  # Row by index


      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    Berlin
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Name       Alice
Age           25
City    New York
Name: 0, dtype: object
Name      Bob
Age        30
City    Paris
Name: 1, dtype: object


In [35]:
!pip install tensorflow


In [37]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor)

# Perform basic operations on tensors
tensor_sum = tf.reduce_sum(tensor)
print(tensor_sum)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)


In [39]:
import tensorflow as tf
from tensorflow.keras import layers

# Define a simple sequential model
model = tf.keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(784,)),  # Input layer
    layers.Dense(64, activation='relu'),  # Hidden layer
    layers.Dense(10, activation='softmax')  # Output layer (for 10 classes)
])

# Compile the model with loss function, optimizer, and metrics
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Display model architecture
model.summary()


C:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

NameError: name 'x_test' is not defined

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Model architecture
model = models.Sequential()

# First convolutional layer
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(48, 48, 1)))
model.add(layers.MaxPooling2D((2, 2)))

# Second convolutional layer
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Third convolutional layer
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Flatten the output and add dense layers
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.5))  # Dropout for regularization
model.add(layers.Dense(7, activation='softmax'))  # Output layer for 7 emotion classes

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
